#!/usr/bin/env bash

basePath=$BLOG_REPO_DIR

function show_help() {
  echo "Usage: blog [edit|add|push|publish]"
}

function do_edit() {
  drafts=$(echo_drafts)
  if [ ! -z "$1" ]; then
    drafts=$(echo "$drafts" | grep "$1")
  fi
  if [ -z "$drafts" ]; then
    echo "There are no drafts. To create one, please run blog new"
  fi
  edit=""
  for draft in $drafts; do
    if [ -z "$edit" ]; then
      edit="$draft"
    else
      edit=$(echo "$drafts" | fzf)
    fi
  done
  if [ -z "$edit" ];then
    echo "No draft selected"
    exit 1
  fi
  nvim "$edit"
}

function echo_drafts() {
  posts=$(find "$basePath/src/posts" -name '*.md')
  for p in $posts; do
    head $p | grep -q 'draft: true'
    if [ $? -eq "0" ]; then
      echo $p
    fi
  done
}

function do_add(){
  read -p "Post name: " name
  sanitizedName=$(echo -e "$name" | tr '[:space:]' '_')
  echo "POST is named $sanitizedName"
}


case "$1" in
  edit)
    do_edit $2
    ;;
  add)
    do_add $2
    ;;
  publish)
    echo "Publishing a post"
    ;;
  push)
    echo "Updating gh pages"
    ;;
  *)
    show_help
    ;;
esac
